### ISSUE TITLE
Zoom icon color

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/ppr-finder#36]
[Spec. Ref.](https://drive.google.com/file/d/1KMrriwGGoas6ugtJrPe_apiC1EvBGBim/view)  | URL | App Version | Browser (version) - Device
---------- | --- | ----------- | ------------------------ | ------
pg11.3,11.4  | /#/locations |  0.1.4 | Chrome |  Desktop

### Expected Behavior
Icon color should be #0f4d90

### Observed Behavior 
> Steps to Reproduce
n/a

#### Proposed Solution
Change icon color
### Screenshot
1.A 

![finder - color of zoom icons](https://user-images.githubusercontent.com/10891276/34459248-f7ab284a-edb8-11e7-8d4b-ba2745fe14dc.png)

**Comment by bdolly** [comment]
closed w/ a76298b5b5d78800085d211bba85ddf753d6a0ba
