### ISSUE TITLE
Filter style & layout

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/ppr-finder#37]
[Spec. Ref.](https://drive.google.com/file/d/1KMrriwGGoas6ugtJrPe_apiC1EvBGBim/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg18  | /#/programs/athletic |  0.1.4 | Chrome |  Desktop

### Expected Behavior
Should match mocks

### Observed Behavior 
> Steps to Reproduce
1. Open filters

### Screenshot
1.A 
![screencapture-cityofphiladelphia-github-io-ppr-finder-1514694823924](https://user-images.githubusercontent.com/10891276/34459297-6b3a8bec-edba-11e7-8861-25c4c3ebf060.png)

**Comment by bdolly** [comment]
closed w/ a27e0c1cb6dce53d81a6d116ed3f19440dcf12f0
