### ISSUE TITLE
"Programs" "Locations" font family should be Montserrat

### ISSUE THREAD

**Issue by sarahall** [CityOfPhiladelphia/ppr-finder#43]
[Spec. Ref.](https://drive.google.com/file/d/1KMrriwGGoas6ugtJrPe_apiC1EvBGBim/view)  | URL | App Version | Browser (version) - Size | Device
---------- | --- | ----------- | ------------------------ | ------
pg13.1  | /#/programs/ |  0.1.4 | Chrome |  Desktop

### Observed Behavior 
> Steps to Reproduce

### Screenshot
1.A 
![finder- apply opacity](https://user-images.githubusercontent.com/10891276/34459489-ba1f8448-edbe-11e7-822a-63a1754926d1.png)

**Comment by bdolly** [comment]
closed w/ a76298b5b5d78800085d211bba85ddf753d6a0ba
