### ISSUE TITLE
Scroll behavior when clicking on location pin in activity search 

### ISSUE THREAD

**Issue by Arinblack** [CityOfPhiladelphia/ppr-finder#45]
[Spec. Ref.  v1.0.4](https://drive.google.com/file/d/15CBYAYFlovs7OOkizQJogSDNMTYamAAJ/view)  | URL  https://cityofphiladelphia.github.io/ppr-finder/#/activities/athletic| App Version 0.2.5 | Chrome (version) - Size | Device HP Stream 
---------- | --- | ----------- | ------------------------ | ------

### Expected Behavior
Expect static sidebar results when clicking on map pin.

### Observed Behavior
The sidebar results (listings) present as uncontrolled scroll when clicking on pins. 
> Steps to Reproduce

1. Go to finder app
2. Click on an activity category (this bug is not category specific)
3. Move cursor to see hover-state text on returned results. 
4. Click on pin
5. Scrolling begins 

### Screenshot
1.A

**Comment by bdolly** [comment]
closed w/ 52b010be3874bdf7a9df308bf49f37ae9a2d073e
